FROM python:3.7-alpine
WORKDIR /test
COPY requirements.txt /test
RUN pip3 install -r requirements.txt --no-cache-dir
COPY . /test
ADD test_users.py /test
ADD conftest.py /test
ENTRYPOINT ["py.test"]
CMD ["test_users.py"]